// LOCALHOST 
### 
GET http://localhost:8080/contacts 

### 
GET http://localhost:8080/contacts/63ba2c1898a0c4386448e05d

### 
GET http://localhost:8080/contacts/63ba2c1898a0c4386448e05f

### 
GET http://localhost:8080/contacts/63ba2c1898a0c4386448e05e

// PRODUCTION Deploy 
### 
GET https://cse341-week02-ind.onrender.com/contacts

### 
GET https://cse341-week02-ind.onrender.com/contacts/63ba2c1898a0c4386448e05d

### 
GET https://cse341-week02-ind.onrender.com/contacts/63ba2c1898a0c4386448e05f

### 
GET https://cse341-week02-ind.onrender.com/contacts/63ba2c1898a0c4386448e05e